"""Framework algorithms — importing registers them with the factory."""
from . import (  # noqa: F401
    budget_algs,
    channel_algs,
    depthladder_algs,
    depthladder_nonlinear_algs,
    diag_algs,
    display_algs,
    eval_algs,
    evalharness_algs,
    exactrows_algs,
    finebasis_algs,
    finebasis_nonlinear_algs,
    fixedgrid_algs,
    io_algs,
    readout_algs,
    reco_algs,
    ress_algs,
    rowsplit_algs,
    spectrum_algs,
    subbin_algs,
    survival_algs,
    truth_algs,
    zsbasis_algs,
)
